version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./web:/web
            - ./datasetdescriptions:/datasetdescriptions
            - ./etc/site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:fpm
        volumes:
            - ./web:/web
            - ./datasetdescriptions:/datasetdescriptions
            - ./etc/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf