name: Build app and update Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set variables
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=docker_image_php_fpm::ghcr.io/netwerk-digitaal-erfgoed/registry-demo-php-fpm"
          echo "::set-output name=docker_image_nginx::ghcr.io/netwerk-digitaal-erfgoed/registry-demo-nginx"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          # See https://github.com/docker/build-push-action/issues/126.
          driver-opts: image=moby/buildkit:master

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Build and push image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/nginx/Dockerfile
          push: true
          tags: |
            ${{ steps.vars.outputs.docker_image_nginx }}:${{ steps.vars.outputs.sha_short }}
            ${{ steps.vars.outputs.docker_image_nginx }}:latest

      - name: Build and push image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/php-fpm/Dockerfile
          push: true
          tags: |
            ${{ steps.vars.outputs.docker_image_php_fpm }}:${{ steps.vars.outputs.sha_short }}
            ${{ steps.vars.outputs.docker_image_php_fpm }}:latest

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Store DigitalOcean credentials
        run: doctl kubernetes cluster kubeconfig save nde

      - name: Update stateful set
        run: |
          kubectl set image statefulset/registry-demo \
            nginx=${{ steps.vars.outputs.docker_image_nginx }}:${{ steps.vars.outputs.sha_short }} \
            php=${{ steps.vars.outputs.docker_image_php_fpm }}:${{ steps.vars.outputs.sha_short }} \
            --record

      - name: Verify stateful set
        run: kubectl rollout status statefulset/registry-demo
